// Fetch Types
export const API_PRODUCT_START = "API_PRODUCT_START";
export const API_PRODUCT_FILL = "API_PRODUCT_FILL";
export const API_PRODUCT_SUCCESS = "API_PRODUCT_SUCCESS";
export const API_PRODUCT_FAILED = "API_PRODUCT_FAILED";

export const API_USER_START = "API_USER_START";
export const API_USER_FAILED = "API_USER_FAILED";
export const API_USER_SUCCESS = "API_USER_SUCCESS";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const NULLIFY_ERROR = "NULLIFY_ERROR";
